# Point Group Symmetry


Point group symmetry is an important property of molecules widely used in many branches of chemistry: electronic structure, spectroscopy, and crystallography. An individual point group is represented by a set of symmetry operations:

\begin{equation}
\begin{aligned}
L^2 |\Psi\rangle &= L(L+1)|\Psi\rangle\\
L_z |\Psi\rangle &= M_L|\Psi\rangle
\end{aligned}
\end{equation}

## Symmetry Operations and Elements

A group point symmetry operation is an operation that is performed to a molecule which leaves it indistinguishable and superimposable on the original position. Symmetry operations are performed with respect to symmetry elements (points, lines, or planes).

There are five types of symmetry operations including identity, reflection, inversion, proper rotation, and improper rotation. The improper rotation is the sum of a rotation followed by a reflection. The symmetry elements that correspond to the five types of symmetry operations are listed in Table.

- Identity (E)

    Identity element is the basic requirement for the minimal group. The identity operation is doing nothing to the molecule (it doesn't rotate, reflect, or invert...it just is).

\begin{equation}
E=
\begin{pmatrix}
1&0&0\\
0&1&0\\
0&0&1
\end{pmatrix}
\end{equation}

- Inversion (i)

    The inversion operation requires a point of symmetry (a center of symmetry within a molecule). In other words, a point at the center of the molecule that can transform (x,y,z) into (-x,-y,-z) coordinate. and Inversion Center 

\begin{equation}
i=
\begin{pmatrix}
-1&0&0\\
0&-1&0\\
0&0&-1
\end{pmatrix}
\end{equation}

- Proper Rotation and Proper Axis ($C_n$)

    A "proper" rotation is just a simple rotation operation about an axis. The symbol for any proper rotation or proper axis is $C_n$, where n is the degree of rotation. Thus, a 180° rotation is a $C_2$ rotation around a $C_2$ axis, and a 120° rotation is a C3 rotation about a $C_3$ axis $\theta = \frac{2\pi k}{n}$.

\begin{equation}
C_n^k=
\begin{pmatrix}
x^2(1-cos(\theta))+cos(\theta)&xy(1-cos(\theta))+zsin(\theta)&xz(1-cos(\theta))+ysin(\theta)\\
xy(1-cos(\theta))+zsin(\theta)&y^2(1-cos(\theta))+cos(\theta)&yz(1-cos(\theta))+xsin(\theta)\\
xz(1-cos(\theta))-ysin(\theta)&zy(1-cos(\theta))+xsin(\theta)&z^2(1-cos(\theta))+cos(\theta)
\end{pmatrix}
\end{equation}

- Reflection and Symmetry Planes ($\sigma$)
    
    Symmetry planes are mirror planes within the molecule. A reflection operation occurs with respect to a plane of symmetry. reflection plane There are three classes of symmetry elements:

\begin{equation}
\sigma=
\begin{pmatrix}
1-2x^2&-2xy&-2xz\\
-2xy&1-2y^2&-2yz\\
-2xz&-2yz&1-2z^2
\end{pmatrix}
\end{equation}


- Improper rotation ($S_n$)

    Improper rotation is a combination of a rotation with respect to an axis of rotation ($C_n$), followed by a reflection through a plane perpendicular to that $C_n$ axis. In short, and $S_n$ operation is equivalent to Cn followed by  $\sigma_h$ .
    
\begin{equation}
S_n = C_n \sigma_h
\end{equation}


|  Symbol  | Element | Operator Symbol | Operation |
|:--------:|:--------:|:------:|:------|
|E|    Identity   | E | The identity operation|
|i|    Inversion center   | i | Inversion through a center of symmetry|
|$\sigma$|    Symmetry plane   | $\sigma$ | Reflection |
|$C_n$|    Proper Axis   | $C_n^1$ | Rotation by 2π/n angle|
|$S_n$|    Improper Axis   | $S_n^1 = \sigma C_n^1$ | Rotation by 2π/n angle and reflection in the plane perpendicular to the axis |

## Abelian Point Group

In most cases the standard quantum chemical packages can take advantage of Abelian point group to reduce the computational costs. In addition of general group definitions, the binary operation on Abelian groups is commutative. Because these Abelian groups P all have real-valued character tables, the direct product of any irrep $I_j$ with itself gives the trivial irrep $I_0$:

\begin{equation}
\forall I_j: I_j\otimes I_j  = E
\end{equation}

More accurately, D2h and its subgroups -- which means that higher symmetry structures can yield up to a factor of 64 reduction in the computational costs.

- $D_{2h}$ Character Tables in Standary Orientation

|$D_{2h}$ |E|$C_2(z)$|$C_2(y)$|$C_2(x)$|i|$\sigma(xy)$|$\sigma(xz)$|$\sigma(yz)$|linear|quadratic|cubic|
|:--------:|:---:|:---:|:---:|:---:|:---:|:---:|:---:|:---:|:---:|:---:|:---:|
|$A_g$|1|1|1|1|1|1|1|1|-|$x^2,y^2,z^2$|-| 	 	 	 	 	 	 
|$B_{1g}$|1|1|-1|-1|1|1|-1|-1|$R_z$|xy|-|	 	 	 	 	 	 
|$B_{2g}$|1|-1|1|-1|1|-1|1|-1|$R_y$|xz|-|	 	 	 	 	 	 
|$B_{3g}$|1|-1|-1|1|1|-1|-1|1|$R_x$|yz|-| 	 	 	 	 	 
|$A_u$|1|1|1|1|-1|-1|-1|-1|-|-|xyz|	 	 	 	 
|$B_{1u}$|1|1|-1|-1|-1|-1|1|1|z|-|$z^3,y^2z,x^2z$|	 	 	 	 
|$B_{2u}$|1|-1|1|-1|-1|1|-1|1|y|-|$yz^,y^3,x^2y$|	 	 	 	 
|$B_{3u}$|1|-1|-1|1|-1|1|1|-1|x|-|$xz^2,xy^2,z^3$|
 
- Ordering of irreps follows the convention used in Cotton’s Chemical Applications of Group Theory

|  Point Group  |0|1|2|3|4|5|6|7
|:--------:|:---:|:---:|:---:|:---:|:---:|:---:|:---:|:---:|
|$C_1$	|A|	||||||| 	 	 	 	 	 	 
|$C_i$	|$A_g$|$A_u$|||||||	 	 	 	 	 	 
|$C_2$	|A|	B|||||||	 	 	 	 	 	 
|$C_s$	|A'|A''||||||| 	 	 	 	 	 
|$D_2$	|A |$B_1$|$B_2$|$B_3$|||||	 	 	 	 
|$C_{2v}$|$A_1$|$A_2$|$B_1$|	$B_2$|||||	 	 	 	 
|$C_{2h}$|$A_g$|$B_g$|$A_u$|	$B_u$|||||	 	 	 	 
|$D_{2h}$|$A_g$|$B_{1g}$|$B_{2g}$|$B_{3g}$|$A_u$|$B_{1u}$|$B_{2u}$|$B_{3u}$|

## Algorithm

- Moments of Inertia

\begin{equation}
I  = 
\left[
\begin{matrix}
I_{xx}&I_{xy}&I_{xz}\\
I_{yx}&I_{yy}&I_{yz}\\
I_{zx}&I_{zy}&I_{zz}\\
\end{matrix}
\right]
\quad
I  = 
\left[
\begin{matrix}
I_a&0&0\\
0&I_b&0\\
0&0&I_c\\
\end{matrix}
\right]
\end{equation}


PRINCIPLE AXIS: The principle axis of a molecule is the highest order proper rotation axis. For example, if a molecule had C2 and C4 axes, the C4 is the principle axis.

|  Rotor Type  |  |Point Group | 
|:--------|:--------|:--------|
|Linear| $I_a=0$ and $I_b=I_c\neq 0$   |$C_{\infty v}$,$D_{\infty h}$   | 
|Spherical  Top|  $I_a=I_b=I_c$  |$T_d$,$T_h$,$O_h$,$I_h$,K   | 
|Symmetric  Top|    |$C_n$,$C_{nh}$,$C_{nv}$,$D_n$,$D_{nh}$,$D_{nd}$,$S_n$   | 
|Asymmetric  Top|  $I_a<I_b<I_c$  |  $C_1$,$C_s$,$C_i$,$C_n$,$C_{nh}$,$C_{nv}$,$D_n$,$D_{nh}$,$D_{nd}$,$S_n$   | 

In [1]:
import numpy as np
from moha.molecule import Molecule

np.set_printoptions(precision=5,suppress=True)

#geo = [[8,2.,1,0],[8,2,-1,0],[8,-2,-1,0],[8,-2,1,0]]
geo = './data/h2o.xyz'
#geo = './data/pyridine.xyz'

mol = Molecule.build(geo,pg=True)

In [2]:
from moha.symmetry.point_group.point_group import PointGroup


group, mol = PointGroup.build(mol)
print(group)
print(group.label)
print(group.is_group)

for operator in group:
    print(operator.symmetry_element)
    print(operator.order)
    print(operator(mol)==mol)

#print(group.D2h_subgroups)
#print(group.D2h_subgroups.label)

#new_mol = group.reflection_list[0](mol)
#print(mol.geometry)
#print(new_mol.geometry)
#print(new_mol==mol)
#print(group.symmetry_operators)
#print(D2h().E)
#print(D2h().i)
#print(D2h().sigma)
#print(D2h().Cn)
#print(D2h().Sn)

wwfwf [0. 0. 1.]
PointGroup({C_{2}^{1}, C_{2}^{1}, E, sigma, C_{2}^{1}})
D_{2h}
False
[0. 1. 0.]
2
False
[0. 0. 1.]
2
True
1
1
True
[0. 1. 0.]
2
True
[1. 0. 0.]
2
False


In [3]:
from moha.symmetry.point_group.symmetry_operator import *
from moha.symmetry.point_group.point_group import PointGroup

r =  Rotation([0.0,0.0,2.0],4)        
print(r.expansion)



symmetry_operators = [
    Identity(),
    Inversion(),
    Reflection([1.0,0.0,0.0]),
    Reflection([0.0,1.0,0.0]),
    Reflection([0.0,0.0,1.0]),
    Rotation([1.0,0.0,0.0],2),
    Rotation([0.0,1.0,0.0],2),
    Rotation([0.0,0.0,1.0],2)
] 

G = PointGroup(symmetry_operators)
print(G)
print(G.is_group)
print(G.E)
print(G.i)
print(G.sigma)
print(G.Cn)
print(G.Sn)
print("fffffffffffffffff")
print(G.Cn_principals)
print(G.C2_perpendicular)
print(G.sigma_h)
print(G.sigma_v)
print(G.sigma_d)
print("fffffffffffffffff")

[C_{4}^{1}, C_{4}^{2}, C_{4}^{3}]
PointGroup({C_{2}^{1}, C_{2}^{1}, C_{2}^{1}, E, sigma, sigma, sigma, i})
True
[E]
[i]
[sigma, sigma, sigma]
[C_{2}^{1}, C_{2}^{1}, C_{2}^{1}]
[]
fffffffffffffffff
[C_{2}^{1} C_{2}^{1} C_{2}^{1}]
[C_{2}^{1}, C_{2}^{1}]
[sigma]
[sigma, sigma]
[]
fffffffffffffffff


In [4]:
print(G.is_group)
print(G.is_abelian_group)
print(G.subgroups)
print(G.D2h_subgroups)
#print(symmetry_operators[2]==symmetry_operators[2])      
#print(G.subsets)

True
True
[PointGroup({E}), PointGroup({C_{2}^{1}, E}), PointGroup({C_{2}^{1}, E}), PointGroup({C_{2}^{1}, E}), PointGroup({E, sigma}), PointGroup({E, sigma}), PointGroup({E, sigma}), PointGroup({E, i}), PointGroup({C_{2}^{1}, C_{2}^{1}, E, C_{2}^{1}}), PointGroup({C_{2}^{1}, sigma, E, sigma}), PointGroup({C_{2}^{1}, i, E, sigma}), PointGroup({C_{2}^{1}, sigma, E, sigma}), PointGroup({C_{2}^{1}, i, E, sigma}), PointGroup({C_{2}^{1}, i, E, sigma}), PointGroup({C_{2}^{1}, sigma, E, sigma}), PointGroup({C_{2}^{1}, C_{2}^{1}, E, sigma, sigma, C_{2}^{1}, sigma, i})]
[PointGroup({E}), PointGroup({C_{2}^{1}, E}), PointGroup({C_{2}^{1}, E}), PointGroup({E, sigma}), PointGroup({E, sigma}), PointGroup({E, C_{2}^{1}}), PointGroup({E, sigma}), PointGroup({E, i}), PointGroup({C_{2}^{1}, C_{2}^{1}, E, C_{2}^{1}}), PointGroup({C_{2}^{1}, i, E, sigma}), PointGroup({C_{2}^{1}, sigma, E, sigma}), PointGroup({C_{2}^{1}, sigma, E, sigma}), PointGroup({C_{2}^{1}, i, E, sigma}), PointGroup({E, C_{2}^{1}, si

In [5]:

from moha.symmetry.point_group.symmetry_operator import *
import math

mol = mol.translation(mol.center_of_mass)
mol = mol.standary_orientation()
mol = mol.translation(mol.center_of_mass)
value, vector = mol.principal_moments_of_inertia
print(mol.principal_moments_of_inertia)

#mol_new = C2v().reflection_list[1](mol)
#print(np.array(mol_new.geometry))

C2 = Rotation([0,0,1.],2)
mol_new = C2(mol)

print(np.array(mol.geometry))
print(np.array(mol_new.geometry))

print(mol==mol_new)

(array([2.9323 , 5.40913, 8.34142]), array([[0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.]]))
[[ 8.       0.       0.      -0.14321]
 [ 1.       0.       1.63804  1.13657]
 [ 1.       0.      -1.63804  1.13657]]
[[ 8.       0.       0.      -0.14321]
 [ 1.      -0.      -1.63804  1.13657]
 [ 1.       0.       1.63804  1.13657]]
True


In [6]:
# Find the center of mass of the molecule
mol = mol.translation(mol.center_of_mass)
value, vector = mol.principal_moments_of_inertia
print(mol.principal_moments_of_inertia)
print(np.array(mol.geometry))

basis = np.array([vector[:,0],vector[:,2],vector[:,1]])
mol = mol.basis_transformation(basis.T)
v, w = mol.principal_moments_of_inertia
print(mol.principal_moments_of_inertia)
print(np.array(mol.geometry))


C_x = Rotation([1,0,0],2)
C_y = Rotation([0,1,0],2)
C_z = Rotation([0,0,1],2)

sigma_xz = Reflection([0,1,0])
sigma_yz = Reflection([1,0,0])
sigma_xy = Reflection([0,0,1])
new_mol = C_z(mol)
#new_mol = sigma_yz(mol)

#new_mol = C2v(mol).reflection_list[1](mol)
print(np.array(new_mol.geometry))

print(new_mol==mol)

print(sigma_xz.homogeneous_matrix)

(array([2.9323 , 5.40913, 8.34142]), array([[0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.]]))
[[ 8.       0.       0.      -0.14321]
 [ 1.       0.       1.63804  1.13657]
 [ 1.       0.      -1.63804  1.13657]]
(array([2.9323 , 5.40913, 8.34142]), array([[1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.]]))
[[ 8.       0.       0.      -0.14321]
 [ 1.       1.63804  0.       1.13657]
 [ 1.      -1.63804  0.       1.13657]]
[[ 8.       0.       0.      -0.14321]
 [ 1.      -1.63804  0.       1.13657]
 [ 1.       1.63804 -0.       1.13657]]
True
[[ 1.  0.  0.  0.]
 [ 0. -1.  0.  0.]
 [ 0.  0.  1.  0.]
 [ 0.  0.  0.  1.]]


In [7]:
SEA = mol.symmetrically_equivalent_atoms()
sea = SEA[0]
value, vector = sea.principal_moments_of_inertia
print(value)
print(vector)
print(SEA.pg)

from moha.symmetry.point_group.rotation import Rotation
C3 = Rotation(3,vector[:,2])
print(np.array(sea.geometry))
print(np.array(C3(sea).geometry))

print(np.allclose(np.array(sea.geometry),np.array(C3(sea).geometry),3))
print(C3(sea)==sea)


[0. 0. 0.]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


AttributeError: 'list' object has no attribute 'pg'